"""add_contact_fields_to_patients

Revision ID: 4a58f378764e
Revises: 001
Create Date: 2025-11-22 20:16:40.236239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a58f378764e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'profile_picture')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###