"""add_department_doctor_fields_to_patients

Revision ID: 50843258b208
Revises: 4a58f378764e
Create Date: 2025-11-22 20:58:15.831594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50843258b208'
down_revision: Union[str, None] = '4a58f378764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('doctor_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'doctor_name')
    op.drop_column('patients', 'department')
    # ### end Alembic commands ###