"""add_status_field_to_patients

Revision ID: 728cf165a2dd
Revises: b02775cf714f
Create Date: 2026-01-22 23:24:31.476067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728cf165a2dd'
down_revision: Union[str, None] = 'b02775cf714f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'status')
    # ### end Alembic commands ###