"""Add doctor_name and department to MedicalReport

Revision ID: b02775cf714f
Revises: 50843258b208
Create Date: 2025-11-25 18:36:00.808688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02775cf714f'
down_revision: Union[str, None] = '50843258b208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_reports', sa.Column('doctor_name', sa.String(length=255), nullable=True))
    op.add_column('medical_reports', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_reports', 'department')
    op.drop_column('medical_reports', 'doctor_name')
    # ### end Alembic commands ###